### ISSUE TITLE
We need feedback on training materials from a new user

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe-doc#254]
I have asked @KathrynOwen to document some observations about socialisation training. She will use this ticket to provide feedback

# cc
@iyan31 @adissadis

**Comment by KathrynOwen** [comment]
I have collated a bunch of feedback points - some of more importance than others. I am thinking that I will create new tickets for the more important ones so that they can perhaps be more easily actioned and once they have been created I can cross-reference the ticket numbers here. 

As I am still new to all of this, please let me know if there is a more appropriate way to go about it.

**Comment by KathrynOwen** [comment]
See tickets #256 - #260

**Comment by adissadis** [comment]
Hi Kathryn,

Currently we updating InaSAFE Training materials to match with InaSAFE 3.0 and QGIS 2.8. And i'm gonna create some pull request to adding updated material to GitHub so you can see recent image match with InaSAFE 3.0 and QGIS 2.8

**Comment by KathrynOwen** [comment]
Hi Adityo,

I am not sure yet what that all means but ok.

FYI, upon Charlotte's instructions, I have been working with InaSAFE 2.2.3 and QGIS 2.6.1 and thus all my current feedback relates to those versions.

**Comment by Charlotte-Morgan** [comment]
Thank @KathrynOwen,
Lets get you using the latest software now that it has been released.

**Comment by Charlotte-Morgan** [comment]
closing this now
